### ISSUE TITLE
New fork or submitting a pull request?

### ISSUE THREAD

**Issue by ylor** [marielin/GoodNight#2]
Vastly prefer this to the methods used in the original. Will you be submitting a pull request or is the intention here to create a new fork?

Thanks for your work!

**Comment by marielin** [comment]
Thanks for the kind words! I'm still not entirely sure what I want to do with regards to the original repo. I feel like the intention there is a bit different than what I'm going for, but there are some changes I could easily push to the original repo without much effort—like my Kelvin scale. 

What's your opinion on the matter?

**Comment by ylor** [comment]
If you plan to vastly differentiate and rebrand, there's no reason to not make a fork but if you can communicate with the original maintainer and your changes are within his/her ideals for the project, your additions could stand to make a better overall project.

**Comment by marielin** [comment]
Alright, I'll contact Anthony and see what his vision for the project is. Thanks for the opinion!
